### ISSUE TITLE
Erroneous NetworkPolicy scan report on non matching pods

### ISSUE THREAD

**Issue by sgandon** [derailed/popeye#116]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Popepey is indicating *[POP-1200] No pods match Ingress pod selector* when the pod indeed exists and are matching the rule.

Here is the matching rule that is wrongly scanned
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-metrics-scraping
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          networking/namespace: admin
      podSelector:
        matchLabels:
          app: prometheus
```

**To Reproduce**
1. create a similar matching rule in one namespace with one pod 
2. create another namespace with a label `networking/namespace: admin`
3. create a pod in this new namespace with a label `app: prometheus`
4. run popeye

**Expected behavior**
No error should be reported

**Versions (please complete the following information):**
 - OS: OSX 10.15.5
 - Popeye : 0.8.8
 - K8s : v1.16.8-eks-e16311
