### ISSUE TITLE
Support globbing in `exlude`

### ISSUE THREAD

**Issue by johanfleury** [derailed/popeye#12]
I'm running a cluster with pods that are spawned on the fly by an external application. These pods use images tagged `latest` and I'd like to ignore them in Popeye's reports.

All those pods share the same prefix (say `foobar-`) so it'd be nice to have globbing support in the `exclude` lists. That way one could write the following:

```
popeye:
  pod:
    exclude:
      - foobar-*
```
