### ISSUE TITLE
How to exclude several check types not explained in README.md?

### ISSUE THREAD

**Issue by marians** [derailed/popeye#129]
I would like to exclude all these check sections using a config file:

- CLUSTERROLES
- CLUSTERROLEBINDINGS
- PODSECURITYPOLICIES
- ROLES
- ROLEBINDINGS
- SECRETS
- SERVICEACCOUNTS

However I can't find the explanation for doing that in the README. Any help appreciated.

**Comment by marians** [comment]
Found a bit on clusterrolebinding in the 0.8.0 release notes

https://github.com/derailed/popeye/releases/tag/v0.8.0

Based on that, I could figure out the config:

```yaml
popeye:
  excludes:
    v1/pods:
      - name: rx:.*
    apps/v1/deployments:
      - name: rx:.*
    autoscaling/v1/horizontalpodautoscalers:
      - name: rx:.*
    policy/v1beta1/poddisruptionbudgets:
      - name: rx:.*
    v1/services:
      - name: rx:.*
    apps/v1/daemonsets:
      - name: rx:.*
    v1/configmaps:
      - name: rx:.*
    rbac.authorization.k8s.io/v1/clusterroles:
      - name: rx:.*
    rbac.authorization.k8s.io/v1/clusterrolebindings:
      - name: rx:.*
```

Would be nice if the docs could be updated accordingly. Didn't expect to find this in the release notes, and only managed after digging through lots of closed issues.
