### ISSUE TITLE
Incomplete and incorrect Kubernetes RBAC

### ISSUE THREAD

**Issue by bygui86** [derailed/popeye#152]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Kubernetes RBAC seem to be incomplete and incorrect.

**To Reproduce**
Run as Job using RBAC manifests provided by the README.md in the repo:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: popeye
  namespace: popeye
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: popeye
      containers:
        - name: popeye
          image: quay.io/derailed/popeye:v0.9.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/popeye"]
          args:
            - -A
            - --over-allocs
            - -o
            - html
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
---
# Popeye ServiceAccount.
apiVersion: v1
kind:       ServiceAccount
metadata:
  name:      popeye
  namespace: popeye
---
# Popeye needs get/list access on the following Kubernetes resources.
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRole
metadata:
  name: popeye
rules:
- apiGroups: [""]
  resources:
   - configmaps
   - deployments
   - endpoints
   - horizontalpodautoscalers
   - namespaces
   - nodes
   - persistentvolumes
   - persistentvolumeclaims
   - pods
   - secrets
   - serviceaccounts
   - services
   - statefulsets
  verbs:     ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:     ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs:     ["get", "list"]
---
# Binds Popeye to this ClusterRole.
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRoleBinding
metadata:
  name: popeye
subjects:
- kind:     ServiceAccount
  name:     popeye
  namespace: popeye
roleRef:
  kind:     ClusterRole
  name:     popeye
  apiGroup: rbac.authorization.k8s.io
```

**Expected behavior**
Popeye should be able to scan all Kubernetes resources if not differently configured/specified.

**Screenshots**
![Screenshot 2021-01-14 at 17 14 17](https://user-images.githubusercontent.com/22518997/104617626-f4a79b80-568b-11eb-8a5a-ab6741b7db8c.png)

**Suggested fix**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRole
metadata:
  name: popeye
rules:
  # FIXED
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:     ["get", "list"]
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - horizontalpodautoscalers
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs:     ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:     ["get", "list"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs:     ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:     ["get", "list"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs:     ["get", "list"]

  # already present and correct
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:     ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:     ["get", "list"]
```

**Versions (please complete the following information):**
 - OS:   -
 - Popeye:   0.9.0
 - K8s:   v1.17.14
