### ISSUE TITLE
POP-1102 - Message formatting problem

### ISSUE THREAD

**Issue by stephenpope** [derailed/popeye#169]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Looks like a formatting/output bug.

**To Reproduce**
1. Create K3D cluster (K3S v1.20.6)
2. Run Popeye
3. Scroll down to `SERVICES`
4. Shows - `[POP-1102] Use of target port%!(EXTRA string=53, string=UDP:dns:53).`

Yaml scanned:

```yml
spec:
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: metrics
      protocol: TCP
      port: 9153
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  clusterIP: 10.43.0.10
  clusterIPs:
    - 10.43.0.10
  type: ClusterIP
  sessionAffinity: None
```

**Expected behavior**
Assume this should say "Use of target port #%s for service port %s. Prefer named port."

**Screenshots**
![image](https://user-images.githubusercontent.com/689099/119324929-44205880-bc78-11eb-8e04-b299a0542cf3.png)

**Versions (please complete the following information):**
 - OS: OSX
 - Popeye: 0.9.2
 - K8s : 1.20.6+k3s1

**Additional context**
Also warns `[POP-1109] Only one associated endpoint.` .. dont know if this is part of the bug.
