### ISSUE TITLE
DRY up exclusions

### ISSUE THREAD

**Issue by kevin-lindsay-1** [derailed/popeye#198]
I have a few charts for services that have warnings that I can't fix, because there's no configuration for them in the chart's `values`.

In order to quiet the noise from these charts, I need to specify every resource type they create, and then exclude them via name, a la:

```yaml
popeye:
  excludes:
    v1/pods:
    - name: rx:infrastructure/aws-load-balancer-controller.*
    - name: rx:infrastructure/metrics-server.*
    - name: rx:istio-system/istiod.*
    - name: rx:istio-system/istio-ingressgateway.*
    apps/v1/daemonsets:
    - name: rx:infrastructure/aws-load-balancer-controller.*
    - name: rx:infrastructure/metrics-server.*
    - name: rx:istio-system/istiod.*
    - name: rx:istio-system/istio-ingressgateway.*
    apps/v1/deployments:
    - name: rx:infrastructure/aws-load-balancer-controller.*
    - name: rx:infrastructure/metrics-server.*
    - name: rx:istio-system/istiod.*
    - name: rx:istio-system/istio-ingressgateway.*
    v1/serviceaccounts:
    - name: rx:infrastructure/aws-load-balancer-controller.*
    - name: rx:infrastructure/metrics-server.*
    - name: rx:istio-system/istiod.*
    - name: rx:istio-system/istio-ingressgateway.*
    v1/services:
    - name: rx:infrastructure/aws-load-balancer-controller.*
    - name: rx:infrastructure/metrics-server.*
    - name: rx:istio-system/istiod.*
    - name: rx:istio-system/istio-ingressgateway.*
    ...
```

This is pretty bulky.

I can think of two ways to support this:

1. Support a method of reference in sequences. `.gitlab-ci.yml` does this by making their sequences support 1 extra layer of sequences, and then spreads them, so that you can reference an anchor, a la:

```yaml
duplicateNames: &duplicateNames
- name: rx:infrastructure/aws-load-balancer-controller.*
- name: rx:infrastructure/metrics-server.*
- name: rx:istio-system/istiod.*
- name: rx:istio-system/istio-ingressgateway.*

popeye:
  excludes:
    v1/pods:
    - *duplicateNames
    apps/v1/daemonsets:
    - *duplicateNames
    apps/v1/deployments:
    - *duplicateNames
    v1/serviceaccounts:
    - *duplicateNames
    v1/services:
    - *duplicateNames
```

which would be unwrapped as:

```yaml
# just showing the one example
popeye:
  excludes:
    v1/pods:
    - - name: rx:infrastructure/aws-load-balancer-controller.*
      - name: rx:infrastructure/metrics-server.*
      - name: rx:istio-system/istiod.*
      - name: rx:istio-system/istio-ingressgateway.*
```

The sequence containing sequences would then simply be spread into one sequence, so it only supports 2-dimensional lists, but is converted to a 1-dimensional list at runtime. I like this, because it's a pretty clean workaround for what I consider to be a missing feature in yaml.

They also have an `includes` key on a number of maps for imports like this.
 
2. Making resource types to scan support wildcards, like names.

I don't see any documentation on this feature, so I assume it doesn't exist.
