### ISSUE TITLE
False positive on NetworkPolicy using a catch all namespaceSelector

### ISSUE THREAD

**Issue by meier-christoph** [derailed/popeye#202]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Popeye reports the following NetworkPolicy with a false positive on POP-1201.

**To Reproduce**

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo
  namespace: bar
spec:
  podSelector:
    matchLabels:
      app: foo
  ingress:
    - from:
        - namespaceSelector: {}
```

**Expected behavior**
Popeye should support NetworkPolicies that use empty namespaceSelectors and not consider this a warning.

**Versions (please complete the following information):**
 - OS: windows
 - Popeye: 0.9.7
 - K8s: 1.19
