### ISSUE TITLE
Networkpolicy checks misses pods on empty selector

### ISSUE THREAD

**Issue by git-honeybadger** [derailed/popeye#259]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
A common default policy for namespace isolation picks all pods of a namespace with the following selector:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-namespace-isolation
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
```

The code as much as I followed is picking the selector to check for pods, in this case the result would be all pods in the given namespace, yet the code will return no matches. 

**To Reproduce**
1. kubectl apply -f <policy above>
2. create pods in a different namespace to run a curl against an open port on the pod in the namespace you added the policy to 
3.  you cannot reach pods ports from a different namespace
4. popeye reports: [POP-1200] No pods match Ingress pod selector

**Expected behavior**
It should not report the given finding

**Versions (please complete the following information):**
 - OS:         [linux]
 - Popeye  [v0.11.1]
 - K8s         [v1.26.4-eks-0a21954]
 - networkpolicy controller: calico
