### ISSUE TITLE
Filter by code via spinach.yml config file not working in 0.11.1

### ISSUE THREAD

**Issue by aschleifer** [derailed/popeye#264]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I'm trying to filter out certain codes with the `spinach.yml` config file, but I can't get a single one to work.

**To Reproduce**
my `spinach.yml`:
```yaml
popeye:
  exclude:
    autoscaling/v2/horizontalpodautoscalers:
      - name: rx:.*
        codes:
          - 602 # Replicas (%d/%d) at burst will match/exceed cluster CPU(%s) capacity by %s
          - 603 # Replicas (%d/%d) at burst will match/exceed cluster memory(%s) capacity by %s
          - 604 # If ALL HPAs triggered, %s will match/exceed cluster CPU(%s) capacity by %s
          - 605 # If ALL HPAs triggered, %s will match/exceed cluster memory(%s) capacity by %s
    v1/pods:
      - name: rx:.*
        codes:
          - 106 # No resources requests/limits defined
```

The command I execute:
```bash
~/downloads/popeye --file ./spinach.yml --sections horizontalpodautoscalers
```

**Expected behavior**
I would expect not to see any warnings or errors regiarding to the codes 602-605

**Versions (please complete the following information):**
 - OS: Arch Linux
 - Popeye: 0.11.1 (commit 22d0830c2c2000f46137b703276786c66ac90908)
 - K8s: 1.26.7

**Additional question**
Is there more documentation on the config file then what is in the README of the repo? I would like to know what exactly the possible fields are apart from the exclude rules.
