### ISSUE TITLE
Spinach documentation

### ISSUE THREAD

**Issue by howardjones** [derailed/popeye#293]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

I thought it would be simple to exclude some specific alerts, but the combination of incomplete docs and (maybe) out-of-date examples makes creating a spinach.yaml harder than necessary.

**Describe the solution you'd like**
Actual documentation for the spinach.yaml file.  For example:

* in the spinach/ examples directory, the aks and aws examples use a `gvrs` key that is not accepted
* in the README it says you can match `fqns` which seems to be namespaces (all the examples are matching namespaces, anyway). `fqn` is also accepted but not mentioned in the docs. 

Some kind of debug logging to show if excludes are being hit would also help. 

**Describe alternatives you've considered**

**Additional context**

My simple use-case is:
* exclude POP-400 for all secrets in a namespace (we use helm-style secrets as a deployment log), as they will never be referenced
* exclude POP-400 for all secrets named helm.release.* anywhere, as they will never be referenced

```
popeye:
  excludes:
    linters:
      v1/secrets:
        instances:
          # the deploys namespace contains a load of unreferenced secrets and that's OK
          # all the secrets named sh.helm.release.v1.* are OK too
          - fqns: ["rx:^deploys/"]
            codes: [400]
          - fqns: ["rx:sh.helm.release"]
            codes: [400]
```
is not the answer though.

**Comment by derailed** [comment]
@howardjones Tx for this issue! Sorry for the confusion. I'll correct the example but I think the docs are correct. 
I think you are close. As the docs indicate, you need to use the linter name vs gvr.

```yaml
popeye:
  excludes:
    linters:
      secrets:
        instances:
          # the deploys namespace contains a load of unreferenced secrets and that's OK
          # all the secrets named sh.helm.release.v1.* are OK too
          - fqns: [rx:^deploys]
            codes: [400]
          - fqns: [rx:sh.helm.release]
            codes: [400]
```
