### ISSUE TITLE
Popeye showing errors for Complete cronjobs

### ISSUE THREAD

**Issue by jim-barber-he** [derailed/popeye#298]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**

For some reason when evaluating `CRONJOBS`, popeye shows errors for complete jobs.
A Pod produced from a Job that has been created by a CronJob that has finished with a status of `Completed` isn't a problem?

**To Reproduce**

Create a simple cronjob. Something like this should suffice:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 0
      template:
        spec:
          automountServiceAccountToken: false
          containers:
          - command:
            - /usr/bin/sleep
            - "10"
            image: debian:stable-slim
            imagePullPolicy: IfNotPresent
            name: cronjob
          restartPolicy: Never
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
```
And apply it. E.g.: `kubectl apply -f $CRONJOB_YAML`

After the job has run a couple of times, run `popeye -s cronjobs` and you'll see the error.

**Expected behavior**

I don't think cronjobs having completed jobs is a problem?
If so, why?
And if they are, this error doesn't have a POP-???? code that can be used to filter it out.

**Screenshots**

From the example cronjob above:
![image](https://github.com/derailed/popeye/assets/38272327/278ee4b6-6064-4edf-bfe6-b364c74efcb8)

**Versions (please complete the following information):**
 - OS: `Debian 12`
 - Popeye: `0.21.1`
 - K8s: `1.28.8`

**Additional context**
