### ISSUE TITLE
Problem ignoring popeye alert rule

### ISSUE THREAD

**Issue by gabrieloliveers** [derailed/popeye#412]
I have the following problem:

When trying to ignore Popeye's alert rule, which is (POP 1109 - Single endpoint is associated with this service) by passing the specification in the spinach.yml file, it continues to appear in the alert report, and the other alerts it can ignore with the same parameters passed!

![Image](https://github.com/user-attachments/assets/0e3c5187-0317-4663-9691-8d4ae3a6fd21)

 - Popeye: v0.21.5 and v0.21.6
 - K8s: EKS v1.31

I need to resolve this and ignore this alert

**Comment by derailed** [comment]
@gabrieloliveers This is odd. Unable to repro this? Excluding svc code 1109 seems to do the right thing.

```yaml
popeye:
  excludes:
    linters:
      services:
        instances:
          - fqns: [rx:.*]
            codes: [1109, 1102]

      secrets:
        instances:
          - fqns: [rx:sh.helm.release]
            codes: [400]
          - fqns: [rx:^kube-system]
            codes: [400]
```

Please check popeye's logs? Also you can try using traces via `popeye ... -v -1` to see why the exclude rules are not firing for services
