### ISSUE TITLE
Allow suppressing specific checks / reports for specific instances

### ISSUE THREAD

**Issue by djablonski-moia** [derailed/popeye#46]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
Some sanitizers are producing warnings which make sense most of time, but on some objects, I would like to be able to accept those "issues".
For example, the "container runs as root" is very helpful 98% of the times, but some very infrastructure-related pods require this.

**Describe the solution you'd like**
It would be nice if there was a way to skip specific aspects of a sanitizer by given names or regex for objects on which they should not be run, or at least on which they should not be reported (and maybe even not considered for the overall score)

**Describe alternatives you've considered**
Just excluding the objects (e.g. pods) is not enough, since this will ignore all checks on them.

**Additional context**
No additional context.

**Comment by derailed** [comment]
@djablonski-moia You are making an excellent point! Thank you for this. Currently Popeye does offer a regex based exclude (via the spinach file) that allows you to exclude pods based on a regex expression (See docs!)

```yaml
excludes:
  pod:
  - rx: *-telemetry
```

This is ok but not great. It's a blunt implementation that excludes matching pods to ALL checks.
I think we need finer controls here:

```yaml
excludes:
  pod:
   # Exclude all fred pods from security checks  privileged and mounting api token
    rx: fred-*:
      sanitizers:
        security: 
          - 302
          - 301
```
 
I have been thinking about this very issue but haven't come up with a good semantic yet.  As a cluster operator you know some workloads will trigger certain conditions deemed as ok, hence exclude it from the next report. This is tricky as just like pods exclusions this could yield to false positive/negative ;(

If folks out there have opinions/ideas on how to best surface this, I am as ever, all ears!
