### ISSUE TITLE
Warning about helm releases

### ISSUE THREAD

**Issue by sheerun** [derailed/popeye#61]
**Describe the bug**

popeye complains about helm releases that are stored in secrets since 3.0.0:

```
    🔊 [POP-400] Used? Unable to locate resource reference.
  · default/sh.helm.release.v1.external-dns.v4.....................................................🔊
```

**To Reproduce**
1. Install something with helm 3
2. Run popeye

**Expected behavior**
Helm secrets are considered used

**Comment by derailed** [comment]
@sheerun  Same idea as prev issue using excludes for this. Please checkout 0.6.0 for exclusion as helm leverages secrets to store some of the chart info.  Thank you!!

**Comment by mitchellmaler** [comment]
@derailed Do you have an example spinach config to exclude these secrets?

**Comment by derailed** [comment]
@mitchellmaler I think you can do something like this in your spinach.yml file:

```yaml
 ...
 excludes:
   v1/secrets:
     # Using regex excludes referential checks for secrets containing `helm` is their name.
     - name: rx:helm
       codes:
         - 400
```
