### ISSUE TITLE
More control over sanitizers

### ISSUE THREAD

**Issue by plainlystated** [derailed/popeye#96]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
As a new user with an existing (but young) cluster, the results are a bit overwhelming.  My immediate problem with my cluster is evictions, and I want to go through all my pods and make sure:
- resource requests are specified
- resource requests are sane

These two concerns seem to be covered by popeye sanitizers, but I'm sorry to say I have so many other issues that the resource problems are a bit lost.

**Describe the solution you'd like**
It would be great if the spinich config allowed global whitelist/blacklist of sanitizers, so I could focus on one problem at a time and incrementally improve things.  Alternatively, there could be some flag for how "clean" I want things to be, based on my personal level of expertise.  Eg "level 1" looks for pod restarts/evictions/etc.  "level 2" looks for resources being requested & sane.  Etc.  This latter approach would be really helpful, especially if the specifics of what a "level" checks could be tweaked in the config.

**Describe alternatives you've considered**
I tried the info/warn/error switching, but that is too course.  There's always outputting to json and parsing manually, if needed :)

**Additional context**
This tool is a great addition to the ecosystem.  Thanks for your work on it!  Beyond the ostensible goal of cleaning up a cluster, there's another important effect of this project: teaching best practices.

**Comment by derailed** [comment]
@plainlystated Thank you for this issue and your kind words!

 I think this is achievable currently but likely not the granularity or usability you're looking for. Keep in mind the idea here it is the sanitizers goal to highlight as many issues as possible on your cluster.  In the meantime you can `somewhat` achieve these results with a bit more elbow grease. So combining the spinach file and cli flags. ie `popeye -n fred -s po -l warn` should achieve your desired results and you can further tune once you've resolved a set of issues. 

This command will filter by namespace, pods only and warning+ severity level. From there you can further tune the scans by excluding codes in your spinach.yml file for example you can exclude containers probe checks from the scans as follows:

```yaml
# For all blueXXX pods in given namespace exclude probes check codes: 102-104.
popeye:
   excludes:
      v1/pods:
          - name: rx: blue
            codes:
               - 102
               - 103
               - 104
   # As an alternative you can override codes severities and "filter out" codes based on the cli arg level...
   codes:
      102: 1
```
